### ISSUE TITLE
ML Ops Examples

### ISSUE THREAD

**Issue by amitkaps** [amitkaps/mlops#1]
## Examples: ML
- [x] Create Level 1 Example with Penguin Dataset
- [x] Create Level 2 Example with Penguin Dataset
- [ ] Create Level 3 Example with Penguin Dataset

## Examples: Peeling the Onion
Basic Model from sklearn / TSFresh
- [ ] Create Level 2 Example with Onion Dataset
- [ ] Create Level 3 Example with Onion Dataset
- [ ] Create Level 4 Example with Onion Dataset

## Examples: Idli / Dosa
- [ ] Focus on Size - Pruning / Quantisation 
- [ ] Focus on Latency - Size Reduction (above), Batching (Multiple Request)

## Starting Up 
- [ ] Make a CookieCutter for ML Ops Project

## Add Datasets
- [x] Palmerpenguins dataset
- [ ] ML Dataset with 10k rows 
- [ ] DL Dataset

**Comment by anandology** [comment]
For Penguins-level2, do the followin improvements:

- [x] do test/train split, print train and test accuracy
- [x] do grid search on `max_depth`
- [ ] add simple input validations - expect columns to be present and their data types
- [ ] write documentation using mkdocs-material
- [ ] add sample data with handful of rows to the repo, add tests to validate the whole flow, make it part of github workflows
- [ ] when you run train.py, print meaninful context to the console and also generate a markdown report
